blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/LeleDallas/Cards-Against-Humanity/discussions
    about: Please ask and answer questions here.
