name: release-please

on:
  workflow_run:
    workflows: ["Client Coverage", "Server Coverage"]
    types:
      - completed
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Release Please Action
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action